#!/bin/bash
#
# from: https://archlinuxarm.org/forum/viewtopic.php?f=49&t=12185&start=230#p64180
# goes to: /usr/lib/systemd/system-sleep/tegra
#

case "$1" in

  "pre")
    # unload bt modules
    rmmod btmrvl_sdio
    rmmod btmrvl
    ;;

  "post")
    # load bt modules
    modprobe btmrvl
    modprobe btmrvl_sdio
    # change to vt6 and return to vt7 is needed to connect the keyboard
    chvt 6
    chvt 7
    # reload the wifi module
    rmmod mwifiex_sdio
    sleep 1
    modprobe mwifiex_sdio
    ;;

  *)
    ;;

esac
