#!/bin/bash

case "$1" in

  "pre")
    # unload bt modules
    rmmod btmrvl_sdio
    rmmod btmrvl
    rmmod btsdio
    sleep 1
    ;;

  "post")
    # load bt modules
    modprobe btsdio
    modprobe btmrvl
    modprobe btmrvl_sdio
    # reload the wifi module
    rmmod mwifiex_sdio
    sleep 1
    modprobe mwifiex_sdio
    ;;

  *)
    ;;

esac
