#!/bin/bash

case "$1" in

  "pre")
    # unload bt modules
    rmmod btusb
    rmmod btrtl
    rmmod btintel
    rmmod btbcm
    sleep 1
    ;;

  "post")
    # load bt modules
    rmmod btbcm
    rmmod btintel
    rmmod btrtl
    rmmod btusb
    # reload the wifi module
    rmmod mwifiex_pcie
    sleep 1
    modprobe mwifiex_pcie
    ;;

  *)
    ;;

esac
