#!/bin/bash

case "$1" in

  "pre")
    # unload bt modules
    rmmod btusb
    rmmod btrtl
    rmmod btintel
    rmmod btbcm
    sleep 1
    # unload the wifi module
    rmmod mwifiex_pcie
    rmmod mwifiex
    sleep 1
    ;;

  "post")
    # load the wifi module
    modprobe mwifiex_pcie
    sleep 1
    # load bt modules
    modprobe btbcm
    modprobe btintel
    modprobe btrtl
    modprobe btusb
    sleep 1
    ;;

  *)
    ;;

esac
