#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

mkdir -p ${DESTDIR}/lib/firmware/qcom
cp -a /lib/firmware/qcom/msm8998-asus-novago-tp370ql ${DESTDIR}/lib/firmware/qcom
cp -a /lib/firmware/qcom/msm8998-hp-envy-x2 ${DESTDIR}/lib/firmware/qcom
cp -a /lib/firmware/qcom/msm8998-lenovo-miix-630 ${DESTDIR}/lib/firmware/qcom
